apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: envvar-secrets
spec:
  # Reads secrets from environment variables.
  # Set STORAGE_CONNECTION_STRING as an App Service app setting and Dapr
  # will expose it as a secret named "STORAGE_CONNECTION_STRING".
  type: secretstores.local.env
  version: v1
